language: php

php:
  - "5.4"
  - "5.3"

notifications:
  irc: "irc.freenode.net#orchestra-platform"

before_install:
  - cd ../../
  - git clone git://github.com/laravel/laravel.git
  - mv ./orchestral/cello ./laravel/bundles/cello
  - cd ./laravel
  - php artisan bundle:install orchestra
  - echo "<?php return array('orchestra' => array('auto' => true, 'handles' => 'orchestra'), 'cello');" > ./application/bundles.php

script: "phpunit --coverage-text --configuration bundles/cello/phpunit.xml"
