language: php

php:
  - "5.4"
  - "5.3"

before_install:
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ./orchestral/cello ./laravel/bundles/cello
  - echo "<?php return array('orchestra' => array('auto' => true, 'handles' => 'orchestra'), 'cello');" > ./laravel/application/bundles.php
  - cd ./laravel
  - php artisan bundle:install orchestra

script: "php artisan test cello"
